Bump versions, fallback from Scala 3.1.0
Scala 3.1.0 currently causes errors when trying to directly run an app
in IntelliJ:

```
scalac: Error: 'java.lang.String dotty.tools.xsbt.DelegatingReporter.messageAndPos(dotty.tools.dotc.reporting.Message, dotty.tools.dotc.util.SourcePosition, java.lang.String, dotty.tools.dotc.core.Contexts$Context)'
java.lang.NoSuchMethodError: 'java.lang.String dotty.tools.xsbt.DelegatingReporter.messageAndPos(dotty.tools.dotc.reporting.Message, dotty.tools.dotc.util.SourcePosition, java.lang.String, dotty.tools.dotc.core.Contexts$Context)'
	at dotty.tools.xsbt.DelegatingReporter.doReport(DelegatingReporter.java:37)
	at dotty.tools.dotc.reporting.Reporter.go$3$$anonfun$2(Reporter.scala:162)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
	at scala.Option.foreach(Option.scala:437)
	at dotty.tools.dotc.reporting.Reporter.go$1(Reporter.scala:174)
	at dotty.tools.dotc.reporting.Reporter.issueIfNotSuppressed(Reporter.scala:193)
	at dotty.tools.dotc.reporting.Reporter.report(Reporter.scala:196)
	at dotty.tools.dotc.report$.issueWarning(report.scala:24)
	at dotty.tools.dotc.report$.warning(report.scala:59)
	at dotty.tools.dotc.config.CliCommand.checkUsage$$anonfun$1(CliCommand.scala:168)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at dotty.tools.dotc.config.CliCommand.checkUsage(CliCommand.scala:168)
	at dotty.tools.dotc.config.CliCommand.checkUsage$(CliCommand.scala:13)
	at dotty.tools.dotc.config.CompilerCommand.checkUsage(CompilerCommand.scala:12)
	at dotty.tools.dotc.Driver.setup(Driver.scala:87)
	at dotty.tools.xsbt.CompilerBridgeDriver.run(CompilerBridgeDriver.java:63)
	at dotty.tools.xsbt.CompilerBridge.run(CompilerBridge.java:22)
	at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:92)
	at org.jetbrains.jps.incremental.scala.local.IdeaIncrementalCompiler.compile(IdeaIncrementalCompiler.scala:57)
	at org.jetbrains.jps.incremental.scala.local.LocalServer.doCompile(LocalServer.scala:52)
	at org.jetbrains.jps.incremental.scala.local.LocalServer.compile(LocalServer.scala:30)
	at org.jetbrains.jps.incremental.scala.remote.Main$.compileLogic(Main.scala:207)
	at org.jetbrains.jps.incremental.scala.remote.Main$.$anonfun$handleCommand$1(Main.scala:190)
	at org.jetbrains.jps.incremental.scala.remote.Main$.decorated$1(Main.scala:180)
	at org.jetbrains.jps.incremental.scala.remote.Main$.handleCommand(Main.scala:187)
	at org.jetbrains.jps.incremental.scala.remote.Main$.serverLogic(Main.scala:163)
	at org.jetbrains.jps.incremental.scala.remote.Main$.nailMain(Main.scala:103)
	at org.jetbrains.jps.incremental.scala.remote.Main.nailMain(Main.scala)
	at jdk.internal.reflect.GeneratedMethodAccessor14.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.martiansoftware.nailgun.NGSession.run(NGSession.java:319)
```